### PR TITLE
Implement `r=me`

### LINKED ISSUE #14: Implement `r=me`
When receiving `r=me`, frau should assign the person making that comment(if he is a reviewer).
At now, frau tells reviewer as `me`, this is bad.

### PR DESCRIPTION
**Pull request by JohnTitor**
Perhaps work

Fixes #14

### CODE REVIEW

**Comment by JohnTitor** [comment]
r+

**Comment by JohnTitor** [comment]
@KoujiroFrau r+

**Comment by KoujiroFrau** [comment]
:pushpin: Commit b1d1f7847e8a85dfde020083227668d94838060c has been approved by `JohnTitor`

**Comment by KoujiroFrau** [comment]
:hourglass: b1d1f7847e8a85dfde020083227668d94838060c has been merged into the auto branch f03393e73d044119c668c5aea32829f830777611

**Comment by KoujiroFrau** [comment]
:tada: The result of what tried to merge this pull request is `success`.

**Comment by JohnTitor** [comment]
@KoujiroFrau r=me

**Comment by KoujiroFrau** [comment]
:pushpin: Commit b1d1f7847e8a85dfde020083227668d94838060c has been approved by `me`

**Comment by JohnTitor** [comment]
@KoujiroFrau r-

**Comment by KoujiroFrau** [comment]
:outbox_tray: This has been cancelled from the approved queue by `JohnTitor`

**Comment by JohnTitor** [comment]
@KoujiroFrau r=me

**Comment by KoujiroFrau** [comment]
:pushpin: Commit b1d1f7847e8a85dfde020083227668d94838060c has been approved by `me`

**Comment by JohnTitor** [comment]
@KoujiroFrau r=me

**Comment by KoujiroFrau** [comment]
:pushpin: Commit b1d1f7847e8a85dfde020083227668d94838060c has been approved by `me`

**Comment by JohnTitor** [comment]
@KoujiroFrau r-

**Comment by KoujiroFrau** [comment]
:outbox_tray: This has been cancelled from the approved queue by `JohnTitor`

**Comment by JohnTitor** [comment]
@KoujiroFrau r=me

**Comment by KoujiroFrau** [comment]
:pushpin: Commit b1d1f7847e8a85dfde020083227668d94838060c has been approved by JohnTitor

**Comment by JohnTitor** [comment]
@KoujiroFrau r-

**Comment by KoujiroFrau** [comment]
:outbox_tray: This has been cancelled from the approved queue by `JohnTitor`

**Pull request merged**
