### PR TITLE
docs: Change to frau

### LINKED ISSUE #2: Change CI badge from original to forked
tora, tora, tora!

### PR DESCRIPTION
**Pull request by JohnTitor**
Fixes #2 

r? @JohnTitor

### CODE REVIEW

**Comment by JohnTitor** [comment]
hoge

r? @JohnTitor

**Comment by JohnTitor** [comment]
Success to parse one by one line! Great!

@KoujiroFrau r+

**Comment by KoujiroFrau** [comment]
:pushpin: Commit 03b258c6446b7debc0ba1f060545b32173232279 has been approved by `JohnTitor`

**Comment by KoujiroFrau** [comment]
:hourglass: 03b258c6446b7debc0ba1f060545b32173232279 has been merged into the auto branch 95730b02a6e85b015f142514299d4a38415df72c

**Comment by KoujiroFrau** [comment]
:tada: The result of what tried to merge this pull request is `success`.

**Comment by JohnTitor** [comment]
@KoujiroFrau r=foo

**Comment by KoujiroFrau** [comment]
:pushpin: Commit 03b258c6446b7debc0ba1f060545b32173232279 has been approved by `foo`

**Comment by JohnTitor** [comment]
@KoujiroFrau r-

**Comment by KoujiroFrau** [comment]
:outbox_tray: This has been cancelled from the approved queue by `JohnTitor`

**Pull request merged**
