### PR TITLE
minor: Add test user

### PR DESCRIPTION
**Pull request by JohnTitor**
For testing, I added test user in OWNERS.json.

r? @JohnTitor

### CODE REVIEW

**Comment by JohnTitor** [comment]
okay,

@KoujiroFrau r+

**Comment by KoujiroFrau** [comment]
:pushpin: Commit 8d0ffe62e8130d9cf76c9394f705c31e6a3406d5 has been approved by `JohnTitor`

**Comment by KoujiroFrau** [comment]
:hourglass: 8d0ffe62e8130d9cf76c9394f705c31e6a3406d5 has been merged into the auto branch 014c539b6b11b9b6d9b05b40fc54edd7a108c802

**Comment by KoujiroFrau** [comment]
:tada: The result of what tried to merge this pull request is `success`.

**Pull request merged**
