### PR TITLE
feat: Parse one by one line

### LINKED ISSUE #1: Parse one by one line
At now, this bot parses first line only.
It's a bother to separate comment and command.

### PR DESCRIPTION
**Pull request by JohnTitor**
Fixes #1

### CODE REVIEW

**Comment by JohnTitor** [comment]
@KoujiroFrau r+

**Comment by KoujiroFrau** [comment]
:pushpin: Commit 36c19dd84cc17ac3d0f886ed44e0205a850e29b7 has been approved by `JohnTitor`

**Comment by KoujiroFrau** [comment]
:hourglass: 36c19dd84cc17ac3d0f886ed44e0205a850e29b7 has been merged into the auto branch 49d36e69a324e1b07f22457f9fb0ae7b091d6777

**Comment by KoujiroFrau** [comment]
:tada: The result of what tried to merge this pull request is `success`.

**Pull request merged**
