### PR TITLE
fix: Add backquotes

### LINKED ISSUE #14: Implement `r=me`
When receiving `r=me`, frau should assign the person making that comment(if he is a reviewer).
At now, frau tells reviewer as `me`, this is bad.

### PR DESCRIPTION
**Pull request by JohnTitor**
Fixes #14

### CODE REVIEW

**Comment by JohnTitor** [comment]
@KoujiroFrau r+

**Comment by KoujiroFrau** [comment]
:pushpin: Commit a91268e66e8ea87d035ca238ddc86f6cbb04e544 has been approved by `JohnTitor`

**Comment by KoujiroFrau** [comment]
:hourglass: a91268e66e8ea87d035ca238ddc86f6cbb04e544 has been merged into the auto branch db477c433867f7b4d1c631efbbfd52c344bc0363

**Comment by KoujiroFrau** [comment]
:tada: The result of what tried to merge this pull request is `success`.

**Pull request merged**
